CREATE TABLE `experimentAssignments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`experimentId` varchar(64) NOT NULL,
	`userId` int,
	`sessionId` varchar(64) NOT NULL,
	`variantId` varchar(32) NOT NULL,
	`assignedAt` timestamp NOT NULL DEFAULT (now()),
	`exposedAt` timestamp,
	`exposed` boolean DEFAULT false,
	CONSTRAINT `experimentAssignments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `experiments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`experimentId` varchar(64) NOT NULL,
	`name` varchar(256) NOT NULL,
	`description` text,
	`hypothesis` text,
	`status` enum('draft','running','paused','completed') DEFAULT 'draft',
	`trafficPercent` int DEFAULT 100,
	`controlPercent` int DEFAULT 50,
	`targetCountries` json,
	`targetUserTypes` json,
	`primaryMetric` varchar(64) DEFAULT 'pay_cvr',
	`secondaryMetrics` json,
	`guardrailMetrics` json,
	`mdePercent` decimal(5,2) DEFAULT '1.50',
	`confidenceLevel` decimal(5,2) DEFAULT '0.95',
	`statisticalPower` decimal(5,2) DEFAULT '0.80',
	`attributionWindowHours` int DEFAULT 24,
	`startDate` timestamp,
	`endDate` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `experiments_id` PRIMARY KEY(`id`),
	CONSTRAINT `experiments_experimentId_unique` UNIQUE(`experimentId`)
);
--> statement-breakpoint
CREATE TABLE `hotels` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(256) NOT NULL,
	`nameEn` varchar(256),
	`city` varchar(128) NOT NULL,
	`country` varchar(128) NOT NULL,
	`address` text NOT NULL,
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`starRating` int NOT NULL,
	`reviewScore` decimal(3,1),
	`reviewCount` int DEFAULT 0,
	`imageUrl` text,
	`images` json,
	`amenities` json,
	`description` text,
	`descriptionEn` text,
	`policyText` text,
	`policyTextEn` text,
	`nearbyLandmarks` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `hotels_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderNumber` varchar(32) NOT NULL,
	`userId` int,
	`sessionId` varchar(64),
	`hotelId` int NOT NULL,
	`roomId` int NOT NULL,
	`checkIn` timestamp NOT NULL,
	`checkOut` timestamp NOT NULL,
	`guestCount` int NOT NULL,
	`guestName` varchar(128) NOT NULL,
	`guestEmail` varchar(320) NOT NULL,
	`guestPhone` varchar(32),
	`guestCountry` varchar(64),
	`specialRequests` text,
	`basePrice` decimal(10,2) NOT NULL,
	`taxAmount` decimal(10,2) NOT NULL,
	`feeAmount` decimal(10,2) NOT NULL,
	`totalPrice` decimal(10,2) NOT NULL,
	`currency` varchar(8) DEFAULT 'USD',
	`status` enum('pending','confirmed','cancelled','completed') DEFAULT 'pending',
	`paymentStatus` enum('unpaid','paid','refunded') DEFAULT 'unpaid',
	`variantId` varchar(32),
	`experimentId` varchar(64),
	`attributionSource` varchar(64),
	`attributionTimestamp` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `orders_id` PRIMARY KEY(`id`),
	CONSTRAINT `orders_orderNumber_unique` UNIQUE(`orderNumber`)
);
--> statement-breakpoint
CREATE TABLE `policyAnalysis` (
	`id` int AUTO_INCREMENT NOT NULL,
	`hotelId` int NOT NULL,
	`roomId` int,
	`cancellationType` varchar(32),
	`freeCancelUntil` varchar(128),
	`penaltyRules` json,
	`taxPayMode` varchar(32),
	`estimatedTaxRange` varchar(64),
	`includedItems` json,
	`excludedItems` json,
	`idDocType` varchar(64),
	`idMinValidMonths` int,
	`idSpecialNotes` text,
	`cancellationConfidence` decimal(3,2),
	`taxConfidence` decimal(3,2),
	`idConfidence` decimal(3,2),
	`evidenceSpans` json,
	`sourceText` text,
	`analysisMethod` varchar(32),
	`llmLatencyMs` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `policyAnalysis_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `rooms` (
	`id` int AUTO_INCREMENT NOT NULL,
	`hotelId` int NOT NULL,
	`name` varchar(256) NOT NULL,
	`nameEn` varchar(256),
	`description` text,
	`basePrice` decimal(10,2) NOT NULL,
	`taxAmount` decimal(10,2) NOT NULL,
	`feeAmount` decimal(10,2) NOT NULL,
	`currency` varchar(8) DEFAULT 'USD',
	`maxGuests` int DEFAULT 2,
	`bedType` varchar(64),
	`roomSize` int,
	`amenities` json,
	`imageUrl` text,
	`inventory` int DEFAULT 10,
	`freeCancellation` boolean DEFAULT false,
	`freeCancelUntil` varchar(64),
	`cancellationPenalty` text,
	`payAtProperty` boolean DEFAULT false,
	`prepayRequired` boolean DEFAULT true,
	`depositRequired` boolean DEFAULT false,
	`depositAmount` decimal(10,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `rooms_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `trackingEvents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`eventName` varchar(64) NOT NULL,
	`userId` int,
	`sessionId` varchar(64) NOT NULL,
	`timestamp` timestamp NOT NULL DEFAULT (now()),
	`hotelId` int,
	`roomId` int,
	`orderId` int,
	`variantId` varchar(32),
	`experimentId` varchar(64),
	`confidenceBucket` varchar(32),
	`properties` json,
	`pageUrl` text,
	`referrer` text,
	`userAgent` text,
	`deviceType` varchar(32),
	`country` varchar(64),
	`language` varchar(16),
	CONSTRAINT `trackingEvents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `users` ADD `country` varchar(64);--> statement-breakpoint
ALTER TABLE `users` ADD `language` varchar(16);